# Generated by Django 5.1.7 on 2025-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='RECEIVED', max_length=50)),
            ],
        ),
    ]
