# Generated by Django 5.1.7 on 2025-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedstock',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
