# Generated by Django 5.1.7 on 2025-03-28 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromsstock',
            name='warehouse_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the transaction was recorded in the system')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('RELEASE', 'Release')], max_length=10)),
                ('warehouse_id', models.CharField(db_index=True, help_text='Identifier of the stock batch/location involved', max_length=100)),
                ('production_code', models.CharField(max_length=100)),
                ('date_of_transaction', models.DateField(help_text='Date entered on the form for this transaction')),
                ('product', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=100)),
                ('pallet_position', models.CharField(max_length=50)),
                ('status', models.CharField(help_text='Status associated with this specific transaction (e.g., NEW, DELIVERY)', max_length=50)),
                ('quantity_change', models.IntegerField(help_text='The amount received (+) or released (-)')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_history_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock History',
                'ordering': ['-timestamp'],
            },
        ),
    ]
