# Generated by Django 5.1.7 on 2025-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasedstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='releasedstock',
            name='production_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
